[tool.bumpversion]
current_version = "1.7.0"
commit = true
message = "Update version {current_version} -> {new_version}"

[[tool.bumpversion.files]]
filename = "ibm_continuous_delivery/version.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"

[[tool.bumpversion.files]]
filename = "setup.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"

[[tool.bumpversion.files]]
filename = "README.md"
search = "{current_version}"
replace = "{new_version}"
